# Generated by Django 2.2 on 2021-08-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210818_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='users',
            new_name='user',
        ),
    ]
